### ISSUE TITLE
Possible to go from kallisto pseudo output to bus file?

### ISSUE THREAD

**Issue by biobenkj** [BUStools/BUSpaRse#8]
BUSpaRse is awesome! Is it possible to go from kallisto pseudo output to a bus format using the TCC matrix, etc.?

Thanks!

**Comment by lambdamoses** [comment]
You can't go from TCC matrix back to the BUS file, since in TCC matrix, which UMI each transcript is associated with is lost. Also, by default, in this package, if the same UMI maps to multiple ECs and the intersection of transcripts in those ECs is empty, then that UMI is discarded, so it won't count in the TCC matrix, so can't be recovered from the TCC matrix. Given the intersections taken over the ECs when the same UMI maps to multiple ECs, the original ECs the reads mapped to before taking intersections are lost. 

But why do you want to convert TCC matrix to BUS format? Or do you actually want to read the kallisto pseudo output into R as a dgCMatrix while `tximport` only supports the kallisto quant output?
