### ISSUE TITLE
Error when writing files in get_velocity files

### ISSUE THREAD

**Issue by cnk113** [BUStools/BUSpaRse#9]
Hello,

I'm trying to get the output from get_velocity_files, but I get an error when outputting the tr2g.tsv.
Specifically I'm getting:
```
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
```
The annotation I'm using is Ensembl v99 for hg38 with the UCSC hg38 assembly.

Thanks

**Comment by lambdamoses** [comment]
I recently updated this package to filter biotypes in tr2g functions. If you filter biotypes, columns for biotypes will be added to `tr2g_cdna`, while `tr2g_intron` only has the transcript and gene columns, causing this error. I'll fix this tomorrow. If you urgently want to use this function, please install an older version of this package with `devtools::install_github("BUStools/BUSpaRse", ref = "1aac9bb")`. Don't use the Bioconductor 3.10 version for this function; this function in that version gives incorrect results for minus strand genes, which was fixed in the `1aac9bb` version.
